name: mydrupal9
recipe: drupal9
config:
  php: '7.3'
  composer_version: '2.0.7'
  via: apache:2.4
  webroot: web
  database: mysql:5.7
  drush: false
  xdebug: false
services:
  appserver:
    build:
      composer install
    overrides:
      image: lando/php:7.3-with-node12
      build:
        context: ./
        dockerfile: Dockerfile.node
tooling:
  node:
    service: appserver
  npm:
    service: appserver