name: mydrupal9
recipe: drupal9
proxy:
  appserver:
    - drupal9.lndo.site
  cli:
    - bs.lndo.site
config:
  php: '7.3'
  composer_version: '2.0.7'
  via: apache:2.4
  webroot: web
  database: mysql:5.7
  drush: false
  xdebug: false
services:
  appserver:
    build:
      composer install
  cli:
    type: node:12
    scanner: false
    ssl: true
    sslExpose: false
    overrides:
      ports:
        - '3000:3000'
tooling:
  node:
    service: cli
  npm:
    service: cli