FROM devwithlando/php:7.3-apache-2

# Choose the major node version
ENV NODE_VERSION=12

# Install node
RUN curl -sL "https://deb.nodesource.com/setup_${NODE_VERSION}.x" | bash - \
  && apt-get install -y nodejs

# EXPOSE 53
# ports: 
#   3000:3000

